### ISSUE TITLE
Font awesome icons don't show up in pdf after puppeteer

### ISSUE THREAD

**Issue by yuchenliu15** [biosan/jsonresume-theme-macchiato#4]
Icons appear perfectly in the HTML document but went missing in the pdf.
However, when I clone the repo and run puppeteer under the repo's directory, the icons appera in PDF version.

**Comment by biosan** [comment]
I had this issue sometimes, but it usually "fixed its self" on a second run, and I always suspected that it was is in some way related to the fact that the icons are downloaded from FontAwesome and sometimes puppeteer times out.

But you are reporting a systematic error, so probably timing out is not the problem.

I'll investigate this issue in the coming days and report back here.

**Comment by bn3t** [comment]
You need to add these parameters to the puppeteer command when you generate the pdf. resume-cli has it by default.

    --wait-until networkidle0

**Comment by biosan** [comment]
Thank you very much @bn3t for the solution, I just updated the README.

Sorry @yuchenliu15 for the very very late response, when you opened the issue I just started a new job and you know... life gets in the way.
